ALTER TYPE "AttemptStatus" RENAME VALUE 'RECORDED' TO 'PENDING';
ALTER TYPE "AttemptStatus" RENAME VALUE 'ANALYZED' TO 'SCORED';
ALTER TYPE "AttemptStatus" RENAME VALUE 'REVIEWED' TO 'FAILED';

CREATE TYPE "FeedbackCode" AS ENUM (
  'PITCH_STEADY',
  'PITCH_VARIATION_REQUIRED',
  'TIMING_REPEAT_REQUIRED',
  'CLARITY_RETRY_REQUIRED',
  'ENERGY_INCREASE_REQUIRED'
);

ALTER TABLE "attempts"
ADD COLUMN "media_path" TEXT;

ALTER TABLE "voice_analysis_results"
ADD COLUMN "feedback_code" "FeedbackCode" NOT NULL DEFAULT 'PITCH_STEADY';
