FEEDBACK_CODES = [
    "PITCH_STEADY",
    "PITCH_VARIATION_REQUIRED",
    "TIMING_REPEAT_REQUIRED",
    "CLARITY_RETRY_REQUIRED",
    "ENERGY_INCREASE_REQUIRED",
]

DEFAULT_FEEDBACK_CODE = "PITCH_STEADY"
